<?php

namespace AppBundle\Repository;

/**
 * InvoiceRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRowRepository extends \Doctrine\ORM\EntityRepository
{
}
